=== martgra/NAN3000/webroot/dbDTD.dtd
<!ELEMENT testb (Informasjon*)>
<!ELEMENT Informasjon (ID,Navn?,Telefon)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT Navn (#PCDATA)>
<!ELEMENT Telefon (#PCDATA)>

=== martgra/NAN3000/webroot/xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE testb SYSTEM "dbDTD.dtd">
<testb>
<Informasjon>
<ID>1</ID>
<Navn>test</Navn>
<Telefon>94033153</Telefon>
</Informasjon>
<Informasjon>
<ID>2</ID>
<Navn>te1st</Navn>
<Telefon>94033133</Telefon>
</Informasjon>
<Informasjon>
<ID>3</ID>
<Navn>te3st</Navn>
<Telefon>94033333</Telefon>
</Informasjon>
</testb>
